######################################################################
# Automatically generated by qmake (3.0) Sun Oct 16 14:11:04 2016
######################################################################

TEMPLATE = app
TARGET = qzhuyin
INCLUDEPATH += .
QT += gui widgets

# Input
HEADERS += ast.h \
           astprinter.h \
           qzy2ast.h \
           zhchar.h
SOURCES += ast.cpp \
           astprinter.cpp \
           qzhuyin.cpp \
           qzy2ast.cpp \
           zhchar.cpp
