######################################################################
# Automatically generated by qmake (3.0) Sun Oct 16 14:11:04 2016
######################################################################

TEMPLATE = app
TARGET = zhuyin-lookup
INCLUDEPATH += .

# Input
RESOURCES += zhuyin-lookup.qrc
SOURCES += zhuyin-lookup.cpp
